<?php

namespace test\formuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * prostecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prostecRepository extends EntityRepository
{
}