parameters:
#    tuto_user.example.class: Tuto\UserBundle\Example

services:
#    tuto_user.example:
#        class: %tuto_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
